[project]
name = "furia-fan-insights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.6",
    "notebook>=7.4.1",
    "pandas>=2.2.3",
    "pillow>=11.2.1",
]
